import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';


// I testi stanno nel catalogo (i18n/it|en/dashboardPage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('dashboardPage.title'),
    wealth: tr('dashboardPage.wealth'),
    wealthInfo: tr('dashboardPage.wealthInfo'),
    heroView: tr('dashboardPage.heroView'),
    heroNav: tr('dashboardPage.heroNav'),
    heroCash: tr('dashboardPage.heroCash'),
    heroNavSub: (base: string, dal: string) => tr('dashboardPage.heroNavSub', { base, dal }),
    heroNavHint: tr('dashboardPage.heroNavHint'),
    heroCashSub: tr('dashboardPage.heroCashSub'),
    heroCashHint: tr('dashboardPage.heroCashHint'),
    invested: tr('dashboardPage.invested'),
    cash: tr('dashboardPage.cash'),
    unitValue: tr('dashboardPage.unitValue'),
    twrSince: tr('dashboardPage.twrSince'),
    regime: tr('dashboardPage.regime'),
    regimeOfficial: (dal: string | null) => dal ? tr('dashboardPage.regimeOfficial_since', { dal }) : tr('dashboardPage.regimeOfficial'),
    regimeReconstructed: tr('dashboardPage.regimeReconstructed'),
    engineNotes: tr('dashboardPage.engineNotes'),
    updated: tr('dashboardPage.updated'),
    source: tr('dashboardPage.source'),
    today: tr('dashboardPage.today'),
    dayPnl: tr('dashboardPage.dayPnl'),
    dayPnlWindow: (finestra: string) => tr('dashboardPage.dayPnlWindow', { finestra }),
    inPeriod: { "1S": tr('dashboardPage.inPeriod_1S'), "1M": tr('dashboardPage.inPeriod_1M'), "1A": tr('dashboardPage.inPeriod_1A'), Tutto: tr('dashboardPage.inPeriod_Tutto') } as Record<string, string>,
    periods: tr('dashboardPage.periods'),
    periodAll: tr('dashboardPage.periodAll'),
    spy: tr('dashboardPage.spy'),
    spyHint: tr('dashboardPage.spyHint'),
    spyMissing: tr('dashboardPage.spyMissing'),
    chartHint: tr('dashboardPage.chartHint'),
    positions: tr('dashboardPage.positions'),
    todayToggle: tr('dashboardPage.todayToggle'),
    totalToggle: tr('dashboardPage.totalToggle'),
    changeView: tr('dashboardPage.changeView'),
    detailed: tr('dashboardPage.detailed'),
    stalePrice: tr('dashboardPage.stalePrice'),
    colTitle: tr('dashboardPage.colTitle'),
    colQty: tr('dashboardPage.colQty'),
    colPrice: tr('dashboardPage.colPrice'),
    colTodayPct: tr('dashboardPage.colTodayPct'),
    colTodayEur: tr('dashboardPage.colTodayEur'),
    colValue: tr('dashboardPage.colValue'),
    colPlEur: tr('dashboardPage.colPlEur'),
    colPlPct: tr('dashboardPage.colPlPct'),
    colWeight: tr('dashboardPage.colWeight'),
    openDetail: tr('dashboardPage.openDetail'),
    news: tr('dashboardPage.news'),
    allNews: tr('dashboardPage.allNews'),
    newsEmpty: tr('dashboardPage.newsEmpty'),
    newsLoading: tr('dashboardPage.newsLoading'),
    newsError: tr('dashboardPage.newsError'),
    tonePositive: tr('dashboardPage.tonePositive'),
    toneNegative: tr('dashboardPage.toneNegative'),
    toneNeutral: tr('dashboardPage.toneNeutral'),
    hoursAgo: tr('dashboardPage.hoursAgo'),
    daysAgo: tr('dashboardPage.daysAgo'),
    justNow: tr('dashboardPage.justNow'),
    allocation: tr('dashboardPage.allocation'),
    allocationView: tr('dashboardPage.allocationView'),
    byStock: tr('dashboardPage.byStock'),
    byRegion: tr('dashboardPage.byRegion'),
    heatmap: tr('dashboardPage.heatmap'),
    invested_: tr('dashboardPage.invested_'),
    others: tr('dashboardPage.others'),
    othersStocks: (n: number) => tr('dashboardPage.othersStocks', { n }),
    diversifiedAs: (n: string) => tr('dashboardPage.diversifiedAs', { n }),
    top5: tr('dashboardPage.top5'),
    inCurrency: (pct: string, ccy: string) => tr('dashboardPage.inCurrency', { pct, ccy: ccy === 'EUR' ? tr('dashboardPage.inCurrency_euro') : ccy }),
    regionsMissing: tr('dashboardPage.regionsMissing'),
    heatArea: tr('dashboardPage.heatArea'),
    heatColorTotal: tr('dashboardPage.heatColorTotal'),
    heatColorToday: tr('dashboardPage.heatColorToday'),
    ofPortfolio: tr('dashboardPage.ofPortfolio'),
    risk: tr('dashboardPage.risk'),
    riskLevel: { basso: tr('dashboardPage.riskLevel_basso'), medio: tr('dashboardPage.riskLevel_medio'), alto: tr('dashboardPage.riskLevel_alto') } as Record<string, string>,
    relativeVol: tr('dashboardPage.relativeVol'),
    varConcentration: tr('dashboardPage.varConcentration'),
    inTwoStocks: tr('dashboardPage.inTwoStocks'),
    riskWhyIdio: (beta: string, a: string, b: string) => tr('dashboardPage.riskWhyIdio', { beta, a, b }),
    riskWhyMarket: (beta: string) => tr('dashboardPage.riskWhyMarket', { beta }),
    riskVsSpy: (ratio: string) => tr('dashboardPage.riskVsSpy', { ratio }),
    ofVar: tr('dashboardPage.ofVar'),
    metric: tr('dashboardPage.metric'),
    portfolio: tr('dashboardPage.portfolio'),
    vsSpy: tr('dashboardPage.vsSpy'),
    vsSpyHint: tr('dashboardPage.vsSpyHint'),
    metrics: {
      vol: [tr('dashboardPage.metrics_vol'), tr('dashboardPage.metrics_vol_hint')],
      var95: [tr('dashboardPage.metrics_var95'), tr('dashboardPage.metrics_var95_hint')],
      var99: [tr('dashboardPage.metrics_var99'), tr('dashboardPage.metrics_var99_hint')],
      dd: [tr('dashboardPage.metrics_dd'), tr('dashboardPage.metrics_dd_hint')],
      beta: [tr('dashboardPage.metrics_beta'), tr('dashboardPage.metrics_beta_hint')],
      sharpe: [tr('dashboardPage.metrics_sharpe'), tr('dashboardPage.metrics_sharpe_hint')],
    } as Record<string, [string, string]>,
    riskBasis: (days: number, obs: number | null) => obs ? tr('dashboardPage.riskBasis_obs', { days, obs }) : tr('dashboardPage.riskBasis', { days }),
    riskRecalc: tr('dashboardPage.riskRecalc'),
    riskLoading: tr('dashboardPage.riskLoading'),
    riskUnavailable: tr('dashboardPage.riskUnavailable'),
    events: tr('dashboardPage.events'),
    eventsScope: tr('dashboardPage.eventsScope'),
    eventsEmpty: tr('dashboardPage.eventsEmpty'),
    eventsError: tr('dashboardPage.eventsError'),
    earnings: tr('dashboardPage.earnings'),
    earningsScope: tr('dashboardPage.earningsScope'),
    calendar: tr('dashboardPage.calendar'),
    eventsView: tr('dashboardPage.eventsView'),
    earningsEmpty: tr('dashboardPage.earningsEmpty'),
    earningsRow: tr('dashboardPage.earningsRow'),
    estimatedDate: tr('dashboardPage.estimatedDate'),
    estimatedHint: tr('dashboardPage.estimatedHint'),
    todayShort: tr('dashboardPage.todayShort'),
    decisions: tr('dashboardPage.decisions'),
    decisionsHint: tr('dashboardPage.decisionsHint'),
    refresh: tr('dashboardPage.refresh'),
    refreshing: tr('dashboardPage.refreshing'),
    runCommittee: tr('dashboardPage.runCommittee'),
    runStarting: tr('dashboardPage.runStarting'),
    runActive: tr('dashboardPage.runActive'),
    runFollow: tr('dashboardPage.runFollow'),
    statusIssues: tr('dashboardPage.statusIssues'),
    staleCount: (n: number) => n === 1 ? tr('dashboardPage.staleCount_one') : tr('dashboardPage.staleCount_other', { n }),
    fxMissing: tr('dashboardPage.fxMissing'),
    partial: tr('dashboardPage.partial'),
    windowHint: tr('dashboardPage.windowHint'),
    partialHint: tr('dashboardPage.partialHint'),
    readFailure: tr('dashboardPage.readFailure'),
    loading: tr('dashboardPage.loading'),
    retry: tr('dashboardPage.retry'),
    close: tr('dashboardPage.close'),
    detailOf: tr('dashboardPage.detailOf'),
    openMarkets: tr('dashboardPage.openMarkets'),
    value: tr('dashboardPage.value'),
    totalPl: tr('dashboardPage.totalPl'),
    weight: tr('dashboardPage.weight'),
    quantity: tr('dashboardPage.quantity'),
    noPositions: tr('dashboardPage.noPositions'),
    itdNotInResponse: tr('dashboardPage.itdNotInResponse'),
    allocationNd: (motivo?: string | null) => tr('dashboardPage.allocationNd', { motivo: motivo || tr('dashboardPage.reasonMissing') }),
    cashWeightNd: (motivo?: string | null) => tr('dashboardPage.cashWeightNd', { motivo: motivo || tr('dashboardPage.reasonMissing') }),
    cashNegative: (peso: string) => tr('dashboardPage.cashNegative', { peso }),
    quoteLegend: tr('dashboardPage.quoteLegend'),
    period_1G: tr('dashboardPage.period_1G'), period_1S: tr('dashboardPage.period_1S'), period_1M: tr('dashboardPage.period_1M'), period_1A: tr('dashboardPage.period_1A'),
    diversifiedFormula: tr('dashboardPage.diversifiedFormula'),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
