import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
import type { FilingStatoUi } from '@/lib/api';
export type Parole = Dizionario;

// I testi stanno nel catalogo (i18n/it|en/favoritesPage.ts); dati chiave e stati del filing
// riusano le etichette di Mercati globali e di Filing. Qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('favoritesPage.title'),
    followed: (n: number) => n === 1 ? tr('favoritesPage.followed_one') : tr('favoritesPage.followed', { n }),
    followedLoading: tr('favoritesPage.followedLoading'),
    followedNd: tr('favoritesPage.followedNd'),
    quotesAt: (h: string) => tr('favoritesPage.quotesAt', { h }),
    quotesLoading: tr('favoritesPage.quotesLoading'),
    refresh: tr('favoritesPage.refresh'),
    addLabel: tr('favoritesPage.addLabel'),
    addHint: tr('favoritesPage.addHint'),
    addResults: tr('favoritesPage.addResults'),
    addNone: (q: string) => tr('favoritesPage.addNone', { q }),
    addFailed: (e: string) => tr('favoritesPage.addFailed', { e }),
    addAction: tr('favoritesPage.addAction'),
    addAlready: tr('favoritesPage.addAlready'),
    adding: tr('favoritesPage.adding'),
    addedToast: (t: string) => tr('favoritesPage.addedToast', { t }),
    addError: (t: string, e: string) => tr('favoritesPage.addError', { t, e }),
    removedToast: (t: string) => tr('favoritesPage.removedToast', { t }),
    removeError: (t: string, e: string) => tr('favoritesPage.removeError', { t, e }),
    closeToast: tr('favoritesPage.closeToast'),
    listTitle: tr('favoritesPage.listTitle'),
    listNote: tr('favoritesPage.listNote'),
    sectorsLabel: tr('favoritesPage.sectorsLabel'),
    all: tr('favoritesPage.all'),
    noSector: tr('favoritesPage.noSector'),
    sortLabel: tr('favoritesPage.sortLabel'),
    sort: { var: tr('favoritesPage.sort_var'), nome: tr('favoritesPage.sort_nome'), data: tr('favoritesPage.sort_data') },
    filterLabel: tr('favoritesPage.filterLabel'),
    filterHint: tr('favoritesPage.filterHint'),
    noNote: tr('favoritesPage.noNote'),
    range52: (p: number) => tr('favoritesPage.range52', { p }),
    range52Nd: tr('favoritesPage.range52Nd'),
    range52Title: tr('favoritesPage.range52Title'),
    filingBadge: tr('favoritesPage.filingBadge'),
    noMatch: tr('favoritesPage.noMatch'),
    noMatchHint: tr('favoritesPage.noMatchHint'),
    showAll: tr('favoritesPage.showAll'),
    loading: tr('favoritesPage.loading'),
    errorTitle: tr('favoritesPage.errorTitle'),
    errorBody: (e: string) => tr('favoritesPage.errorBody', { e }),
    errorList: tr('favoritesPage.errorList'),
    errorListHint: tr('favoritesPage.errorListHint'),
    errorDetail: tr('favoritesPage.errorDetail'),
    retry: tr('favoritesPage.retry'),
    emptyTitle: tr('favoritesPage.emptyTitle'),
    emptyBody: tr('favoritesPage.emptyBody'),
    emptyAdd: tr('favoritesPage.emptyAdd'),
    emptyMarket: tr('favoritesPage.emptyMarket'),
    selectHint: tr('favoritesPage.selectHint'),
    since: (d: string) => tr('favoritesPage.since', { d }),
    noSectorMeta: tr('favoritesPage.noSectorMeta'),
    tradeIdea: tr('favoritesPage.tradeIdea'),
    openMarket: tr('favoritesPage.openMarket'),
    remove: (t: string) => tr('favoritesPage.remove', { t }),
    prevClose: (v: string) => tr('favoritesPage.prevClose', { v }),
    quoteTime: (h: string) => tr('favoritesPage.quoteTime', { h }),
    range52Long: tr('favoritesPage.range52Long'),
    fromLow: (p: number) => tr('favoritesPage.fromLow', { p }),
    low: tr('favoritesPage.low'),
    high: tr('favoritesPage.high'),
    targetMark: tr('favoritesPage.targetMark'),
    quoteMissing: tr('favoritesPage.quoteMissing'),
    quoteMissingBody: (t: string, e: string) => tr('favoritesPage.quoteMissingBody', { t, e }),
    quoteLoading: tr('favoritesPage.quoteLoading'),
    keyData: tr('favoritesPage.keyData'),
    keyDataNote: tr('favoritesPage.keyDataNote'),
    k: {
      cap: tr('marketsPage.stats_cap'), pe: tr('marketsPage.stats_pe'), eve: tr('marketsPage.stats_evEbitda'), div: tr('marketsPage.stats_div'),
      tgt: tr('marketsPage.stats_target'), rec: tr('favoritesPage.k_rec'), beta: tr('marketsPage.stats_beta'), vol: tr('marketsPage.stats_vol'),
    },
    s: {
      cap: tr('favoritesPage.s_cap'), pe: (v: string) => tr('favoritesPage.s_pe', { v }), peNd: tr('favoritesPage.s_peNd'),
      eve: tr('favoritesPage.s_eve'), div: tr('favoritesPage.s_div'), tgt: (v: string) => tr('favoritesPage.s_tgt', { v }),
      nocov: tr('favoritesPage.s_nocov'), rec: tr('favoritesPage.s_rec'), beta: tr('favoritesPage.s_beta'),
      vol: (v: string) => tr('favoritesPage.s_vol', { v }), nd: tr('favoritesPage.s_nd'),
    },
    rec: {
      strong_buy: tr('favoritesPage.rec_strong_buy'), buy: tr('favoritesPage.rec_buy'), hold: tr('favoritesPage.rec_hold'),
      underperform: tr('favoritesPage.rec_underperform'), sell: tr('favoritesPage.rec_sell'), strong_sell: tr('favoritesPage.rec_strong_sell'),
    } as Record<string, string>,
    noteTitle: tr('favoritesPage.noteTitle'),
    noteNote: tr('favoritesPage.noteNote'),
    noteLabel: (t: string) => tr('favoritesPage.noteLabel', { t }),
    notePlaceholder: tr('favoritesPage.notePlaceholder'),
    noteDirty: tr('favoritesPage.noteDirty'),
    noteSaving: tr('favoritesPage.noteSaving'),
    noteSavedNow: tr('favoritesPage.noteSavedNow'),
    noteStored: tr('favoritesPage.noteStored'),
    noteNone: tr('favoritesPage.noteNone'),
    noteSave: tr('favoritesPage.noteSave'),
    noteFailed: (e: string) => tr('favoritesPage.noteFailed', { e }),
    filingTitle: tr('nav.filing'),
    filingNote: tr('favoritesPage.filingNote'),
    filingOpen: tr('favoritesPage.filingOpen'),
    filingInactiveTitle: tr('favoritesPage.filingInactiveTitle'),
    filingInactive: tr('favoritesPage.filingInactive'),
    filingActivate: tr('favoritesPage.filingActivate'),
    filingNoSourceTitle: tr('favoritesPage.filingNoSourceTitle'),
    filingNoSource: (t: string) => tr('favoritesPage.filingNoSource', { t }),
    filingCompared: (d: string) => tr('favoritesPage.filingCompared', { d }),
    filingChanges: (n: number) => n === 1 ? tr('favoritesPage.filingChanges_one') : tr('favoritesPage.filingChanges', { n }),
    filingNoChanges: tr('favoritesPage.filingNoChanges'),
    filingFirst: tr('favoritesPage.filingFirst'),
    filingSource: tr('favoritesPage.filingSource'),
    filingNext: tr('favoritesPage.filingNext'),
    filingLastError: tr('favoritesPage.filingLastError'),
    filingErr: (e: string) => tr('favoritesPage.filingErr', { e }),
    filingLoading: tr('favoritesPage.filingLoading'),
    filingTag: {
      novita: tr('filingPage.tag_novita'), aggiornato: tr('filingPage.tag_aggiornato'), invariato: tr('filingPage.tag_invariato'),
      in_corso: tr('filingPage.tag_in_corso'), primo_confronto: tr('filingPage.tag_primo_confronto'), errore: tr('filingPage.tag_errore'),
      da_confermare: tr('filingPage.tag_da_confermare'), proposta_ai: tr('filingPage.tag_proposta_ai'), senza_fonte: tr('filingPage.tag_senza_fonte'),
      non_attivo: tr('filingPage.tag_non_attivo'), escluso: tr('filingPage.tag_escluso'),
    } as Record<FilingStatoUi, string>,
    profileTitle: tr('favoritesPage.profileTitle'),
    more: tr('favoritesPage.more'),
    less: tr('favoritesPage.less'),
    nd: tr('favoritesPage.nd'),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
