import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';

// I testi stanno nel catalogo (i18n/it|en/factorsPage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('factorsPage.title'),
    window: (p: string | number) => tr('factorsPage.window', { p }),
    holdings: (n: string | number) => tr('factorsPage.holdings', { n }),
    holdingsOne: tr('factorsPage.holdingsOne'),
    modelHint: tr('factorsPage.modelHint'),
    year1: tr('factorsPage.year1'),
    years3: tr('factorsPage.years3'),
    delay: (d: string | number, n: string | number) => tr('factorsPage.delay', { d, n }),
    delayHint: tr('factorsPage.delayHint'),
    delayMissing: tr('factorsPage.delayMissing'),
    views: tr('factorsPage.views'),
    viewBeta: tr('factorsPage.viewBeta'),
    viewFactors: tr('factorsPage.viewFactors'),
    viewSecurities: tr('factorsPage.viewSecurities'),
    method: tr('factorsPage.method'),
    methodWarn: tr('factorsPage.methodWarn'),
    close: tr('factorsPage.close'),
    recalc: tr('factorsPage.recalc'),
    recalcHint: (s: string | number) => tr('factorsPage.recalcHint', { s }),
    phaseFactors: tr('factorsPage.phaseFactors'),
    phaseReconcile: tr('factorsPage.phaseReconcile'),
    phaseWarm: tr('factorsPage.phaseWarm'),
    factorsUnavailable: (e: string | number) => tr('factorsPage.factorsUnavailable', { e }),
    errorMissing: tr('factorsPage.errorMissing'),
    cacheRestoreFailed: (e: string | number) => tr('factorsPage.cacheRestoreFailed', { e }),
    na: tr('factorsPage.na'),
    betaTitle: tr('factorsPage.betaTitle'),
    betaInfo: tr('factorsPage.betaInfo'),
    betaCount: (n: string | number) => tr('factorsPage.betaCount', { n }),
    betaCountOne: tr('factorsPage.betaCountOne'),
    betaReconciled: (n: string | number) => tr('factorsPage.betaReconciled', { n }),
    verdictOk: tr('factorsPage.verdictOk'),
    verdictKo: tr('factorsPage.verdictKo'),
    verdictTitle: (v: string | number) => tr('factorsPage.verdictTitle', { v }),
    verdictPending: tr('factorsPage.verdictPending'),
    verdictInsufficient: tr('factorsPage.verdictInsufficient'),
    insufficientText: tr('factorsPage.insufficientText'),
    unknownText: (v: string | number) => tr('factorsPage.unknownText', { v }),
    verdictMissing: (e: string | number) => tr('factorsPage.verdictMissing', { e }),
    consensus: tr('factorsPage.consensus'),
    consensusInfo: tr('factorsPage.consensusInfo'),
    spreadPill: (v: string | number) => tr('factorsPage.spreadPill', { v }),
    thresholdPill: (v: string | number) => tr('factorsPage.thresholdPill', { v }),
    okText: tr('factorsPage.okText'),
    koText: tr('factorsPage.koText'),
    rulerLabel: tr('factorsPage.rulerLabel'),
    keyReconciled: tr('factorsPage.keyReconciled'),
    keyOutside: tr('factorsPage.keyOutside'),
    keyBand: tr('factorsPage.keyBand'),
    keyThreshold: (v: string | number) => tr('factorsPage.keyThreshold', { v }),
    radioReconciled: tr('factorsPage.radioReconciled'),
    radioOutside: tr('factorsPage.radioOutside'),
    srcFactor3: tr('factorsPage.srcFactor3'),
    srcFactorWindow: (p: string | number) => tr('factorsPage.srcFactorWindow', { p }),
    srcSpy: tr('factorsPage.srcSpy'),
    srcTwr: tr('factorsPage.srcTwr'),
    glossFactor3: tr('factorsPage.glossFactor3'),
    glossFactorWindow: tr('factorsPage.glossFactorWindow'),
    glossSpy: tr('factorsPage.glossSpy'),
    glossTwr: tr('factorsPage.glossTwr'),
    glossOther: tr('factorsPage.glossOther'),
    sourcesFailed: (l: string | number) => tr('factorsPage.sourcesFailed', { l }),
    waiting: tr('factorsPage.waiting'),
    waitingSub: (s: string | number) => tr('factorsPage.waitingSub', { s }),
    betaEmpty: tr('factorsPage.betaEmpty'),
    alphaTitle: tr('factorsPage.alphaTitle'),
    alphaInfo: tr('factorsPage.alphaInfo'),
    sharpeTitle: tr('factorsPage.sharpeTitle'),
    sharpeInfo: tr('factorsPage.sharpeInfo'),
    twoSources: tr('factorsPage.twoSources'),
    gapPill: (v: string | number) => tr('factorsPage.gapPill', { v }),
    gapPp: (v: string | number) => tr('factorsPage.gapPp', { v }),
    gapMissing: tr('factorsPage.gapMissing'),
    gapLabel: tr('factorsPage.gapLabel'),
    alphaA: tr('factorsPage.alphaA'),
    alphaAHow: (n: string | number, p: string | number, d: string | number) => tr('factorsPage.alphaAHow', { n, p, d }),
    alphaB: tr('factorsPage.alphaB'),
    alphaBHow: tr('factorsPage.alphaBHow'),
    sharpeA: tr('factorsPage.sharpeA'),
    sharpeAHow: tr('factorsPage.sharpeAHow'),
    sharpeB: tr('factorsPage.sharpeB'),
    sharpeBHow: (rf: string | number) => tr('factorsPage.sharpeBHow', { rf }),
    notMeasured: tr('factorsPage.notMeasured'),
    noTest: tr('factorsPage.noTest'),
    advUnavailable: (e: string | number) => tr('factorsPage.advUnavailable', { e }),
    riskUnavailable: (e: string | number) => tr('factorsPage.riskUnavailable', { e }),
    profTitle: tr('factorsPage.profTitle'),
    profInfo: tr('factorsPage.profInfo'),
    profNote: tr('factorsPage.profNote'),
    colFactor: tr('factorsPage.colFactor'),
    colNeg: tr('factorsPage.colNeg'),
    colPos: tr('factorsPage.colPos'),
    colDelta: tr('factorsPage.colDelta'),
    deltaHint: tr('factorsPage.deltaHint'),
    deltaBig: tr('factorsPage.deltaBig'),
    glossMKT: tr('factorsPage.glossMKT'),
    glossSMB: tr('factorsPage.glossSMB'),
    glossHML: tr('factorsPage.glossHML'),
    glossRMW: tr('factorsPage.glossRMW'),
    glossCMA: tr('factorsPage.glossCMA'),
    glossMOM: tr('factorsPage.glossMOM'),
    window3Loading: tr('factorsPage.window3Loading'),
    window3Unavailable: (e: string | number) => tr('factorsPage.window3Unavailable', { e }),
    alphaRowTitle: tr('factorsPage.alphaRowTitle'),
    alphaRowRest: tr('factorsPage.alphaRowRest'),
    covTitle: tr('factorsPage.covTitle'),
    covInfo: tr('factorsPage.covInfo'),
    covNote: tr('factorsPage.covNote'),
    covInvested: tr('factorsPage.covInvested'),
    covInvestedSub: (a: string | number) => tr('factorsPage.covInvestedSub', { a }),
    covInvestedSubSkipped: (a: string | number, b: string | number) => tr('factorsPage.covInvestedSubSkipped', { a, b }),
    covNav: tr('factorsPage.covNav'),
    covNavSub: tr('factorsPage.covNavSub'),
    covAnalyzed: tr('factorsPage.covAnalyzed'),
    covCash: tr('factorsPage.covCash'),
    portfolioUnavailable: (e: string | number) => tr('factorsPage.portfolioUnavailable', { e }),
    regTitle: tr('factorsPage.regTitle'),
    regInfo: tr('factorsPage.regInfo'),
    regDatasets: (a: string | number) => tr('factorsPage.regDatasets', { a }),
    regDatasetOne: tr('factorsPage.regDatasetOne'),
    regSkipped: (b: string | number) => tr('factorsPage.regSkipped', { b }),
    regSkippedOne: tr('factorsPage.regSkippedOne'),
    regRowSub: (t: string | number, o: string | number, d: string | number) => tr('factorsPage.regRowSub', { t, o, d }),
    lastData: tr('factorsPage.lastData'),
    lastDataSub: (n: string | number) => tr('factorsPage.lastDataSub', { n }),
    obsRange: tr('factorsPage.obsRange'),
    obsRangeSub: tr('factorsPage.obsRangeSub'),
    noSkipped: tr('factorsPage.noSkipped'),
    noSkippedSub: tr('factorsPage.noSkippedSub'),
    skippedTitle: (n: string | number) => tr('factorsPage.skippedTitle', { n }),
    skippedTitleOne: tr('factorsPage.skippedTitleOne'),
    skippedNoDetail: tr('factorsPage.skippedNoDetail'),
    hmTitle: tr('factorsPage.hmTitle'),
    hmInfo: tr('factorsPage.hmInfo'),
    hmNote: (s: string | number, c: string | number, a: string | number, n: string | number) => tr('factorsPage.hmNote', { s, c, a, n }),
    sortLabel: tr('factorsPage.sortLabel'),
    sortWeight: tr('factorsPage.sortWeight'),
    sortAlpha: tr('factorsPage.sortAlpha'),
    colSecurity: tr('factorsPage.colSecurity'),
    colWeight: tr('factorsPage.colWeight'),
    colAlphaCi: tr('factorsPage.colAlphaCi'),
    colAlpha: tr('factorsPage.colAlpha'),
    colR2Hint: tr('factorsPage.colR2Hint'),
    keyNeg: tr('factorsPage.keyNeg'),
    keyPos: tr('factorsPage.keyPos'),
    keyNs: tr('factorsPage.keyNs'),
    keyAlpha: tr('factorsPage.keyAlpha'),
    cellTitle: (b: string | number, t: string | number) => tr('factorsPage.cellTitle', { b, t }),
    cellNs: tr('factorsPage.cellNs'),
    hmEmpty: tr('factorsPage.hmEmpty'),
    detTitle: tr('factorsPage.detTitle'),
    detDataset: (r: string | number) => tr('factorsPage.detDataset', { r }),
    detFx: tr('factorsPage.detFx'),
    detWeight: (w: string | number) => tr('factorsPage.detWeight', { w }),
    detAlpha: tr('factorsPage.detAlpha'),
    detSig: tr('factorsPage.detSig'),
    detNs: tr('factorsPage.detNs'),
    detCi: (lo: string | number, hi: string | number) => tr('factorsPage.detCi', { lo, hi }),
    detR2Sub: tr('factorsPage.detR2Sub'),
    detObs: tr('factorsPage.detObs'),
    detObsSub: tr('factorsPage.detObsSub'),
    detProfile: tr('factorsPage.detProfile'),
    whiskAria: (n: string | number, v: string | number, lo: string | number, hi: string | number, t: string | number, s: string | number) => tr('factorsPage.whiskAria', { n, v, lo, hi, t, s }),
    whiskSig: tr('factorsPage.whiskSig'),
    whiskZero: tr('factorsPage.whiskZero'),
    whiskNs: tr('factorsPage.whiskNs'),
    mDefs: tr('factorsPage.mDefs'),
    mDefsNote: tr('factorsPage.mDefsNote'),
    mQuality: tr('factorsPage.mQuality'),
    qSig: tr('factorsPage.qSig'),
    qAlpha: tr('factorsPage.qAlpha'),
    qR2: tr('factorsPage.qR2'),
    qOld: tr('factorsPage.qOld'),
    qOldNs: tr('factorsPage.qOldNs'),
    qSat: tr('factorsPage.qSat'),
    mAlign: tr('factorsPage.mAlign'),
    mCost: tr('factorsPage.mCost'),
    mCostText: (s: string | number) => tr('factorsPage.mCostText', { s }),
    mCostRunning: tr('factorsPage.mCostRunning'),
    mGuard: tr('factorsPage.mGuard'),
    // contratto del guardrail beta del 06/10 (fonti insufficienti, intervallo indicativo, punteggio quant)
    holdingsMissing: tr('factorsPage.holdingsMissing'),
    verdictNoClearance: tr('factorsPage.verdictNoClearance'),
    noClearanceText: tr('factorsPage.noClearanceText'),
    radioExcluded: tr('factorsPage.radioExcluded'),
    excludedPill: (n: string | number, m: string | number) => tr('factorsPage.excludedPill', { n, m }),
    obsCount: (n: string | number) => tr('factorsPage.obsCount', { n }),
    excludedNoValue: (l: string | number) => tr('factorsPage.excludedNoValue', { l }),
    notForDecisions: tr('factorsPage.notForDecisions'),
    indicativeRange: tr('factorsPage.indicativeRange'),
    indicativeMedian: (v: string | number) => tr('factorsPage.indicativeMedian', { v }),
    consensusNone: tr('factorsPage.consensusNone'),
    minObsLine: (n: string | number) => tr('factorsPage.minObsLine', { n }),
    regWeightMissing: tr('factorsPage.regWeightMissing'),
    gqReconciled: tr('factorsPage.gqReconciled'),
    gqUnreliable: tr('factorsPage.gqUnreliable'),
    gqInsufficient: tr('factorsPage.gqInsufficient'),
    gqNotComputed: tr('factorsPage.gqNotComputed'),
    gqUnavailable: tr('factorsPage.gqUnavailable'),
    gqNoClearance: tr('factorsPage.gqNoClearance'),
    gqNoRiskSource: tr('factorsPage.gqNoRiskSource'),
    gqUnknown: (c: string | number) => tr('factorsPage.gqUnknown', { c }),
    gqMissing: tr('factorsPage.gqMissing'),
    // revisione del 06/10: osservazioni non verificabili, esito e fonte non riconosciuti
    radioExcludedUnverifiable: tr('factorsPage.radioExcludedUnverifiable'),
    verdictUnknown: tr('factorsPage.verdictUnknown'),
    verdictUnknownCode: (v: string | number) => tr('factorsPage.verdictUnknownCode', { v }),
    srcUnknown: (k: string | number) => tr('factorsPage.srcUnknown', { k }),
  };
}

export type Parole = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Parole>();

export function parole(): Parole {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
