import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';
import type { Periodo } from './calcoli';

export type IdScenario = 'none' | 'shock_3sigma' | 'gfc_2008' | 'covid_2020';

// I testi stanno nel catalogo (i18n/it|en/performancePage.ts): qui solo la forma che le viste usano.
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  return {
    title: tr('performancePage.title'),
    dayPnl: tr('performancePage.dayPnl'),
    dayPnlWindow: (f: string) => tr('performancePage.dayPnlWindow', { f }),
    dayPnlHint: tr('performancePage.dayPnlHint'),
    dayPnlPartial: tr('performancePage.dayPnlPartial'),
    sharpeNoRf: tr('performancePage.sharpeNoRf'),
    dayPnlReadFailed: (e: string) => tr('performancePage.dayPnlReadFailed', { e }),
    views: tr('performancePage.views'),
    viewSheet: tr('performancePage.viewSheet'),
    viewRisk: tr('performancePage.viewRisk'),
    method: tr('performancePage.method'),
    methodWarn: tr('performancePage.methodWarn'),
    close: tr('performancePage.close'),
    refresh: tr('performancePage.refresh'),
    refreshing: tr('performancePage.refreshing'),
    updatedAt: (h: string) => tr('performancePage.updatedAt', { h }),
    period: tr('performancePage.period'),
    periods: { "1S": tr('performancePage.periods_1S'), "1M": tr('performancePage.periods_1M'), "3M": tr('performancePage.periods_3M'), YTD: tr('performancePage.periods_YTD'), Tutto: tr('performancePage.periods_Tutto') } as Record<Periodo, string>,
    periodLong: { "1S": tr('performancePage.periodLong_1S'), "1M": tr('performancePage.periodLong_1M'), "3M": tr('performancePage.periodLong_3M'), YTD: tr('performancePage.periodLong_YTD'), Tutto: tr('performancePage.periodLong_Tutto') } as Record<Periodo, string>,
    shortHistory: (d: string) => tr('performancePage.shortHistory', { d }),
    returnLabel: (p: string) => tr('performancePage.returnLabel', { p }),
    returnInfo: tr('performancePage.returnInfo'),
    unit: tr('performancePage.unit'),
    unitPct: tr('performancePage.unitPct'),
    unitEur: tr('performancePage.unitEur'),
    unitPctHint: tr('performancePage.unitPctHint'),
    unitEurHint: tr('performancePage.unitEurHint'),
    pnlPeriodInfo: tr('performancePage.pnlPeriodInfo'),
    pnlPeriodPartial: (n: number) => tr('performancePage.pnlPeriodPartial', { n }),
    vsSpy: (v: string) => tr('performancePage.vsSpy', { v }),
    spyPill: (v: string) => tr('performancePage.spyPill', { v }),
    maxDd: tr('performancePage.maxDd'),
    maxDdSub: (v: string) => tr('performancePage.maxDdSub', { v }),
    maxDdInfo: tr('performancePage.maxDdInfo'),
    sharpe: tr('performancePage.sharpe'),
    sharpeSub: (rf: string) => tr('performancePage.sharpeSub', { rf }),
    sharpeInfo: tr('performancePage.sharpeInfo'),
    sharpeShort: tr('performancePage.sharpeShort'),
    sinceStart: tr('performancePage.sinceStart'),
    sinceStartSub: (spy: string, d: string) => tr('performancePage.sinceStartSub', { spy, d }),
    sinceStartInfo: (d: string) => tr('performancePage.sinceStartInfo', { d }),
    nav: tr('performancePage.nav'),
    navSub: (n: number | null) => n == null ? tr('performancePage.navSub') : tr('performancePage.navSub_positions', { n }),
    spy: tr('performancePage.spy'),
    spyHint: tr('performancePage.spyHint'),
    spyMissing: (why: string) => tr('performancePage.spyMissing', { why }),
    sma: tr('performancePage.sma'),
    sma20: tr('performancePage.sma20'),
    sma50: tr('performancePage.sma50'),
    portfolio: tr('performancePage.portfolio'),
    spyEur: tr('performancePage.spyEur'),
    reconstructedUntil: (d: string) => tr('performancePage.reconstructedUntil', { d }),
    chartLabel: tr('performancePage.chartLabel'),
    otherMetrics: tr('performancePage.otherMetrics'),
    sinceDate: (d: string) => tr('performancePage.sinceDate', { d }),
    groupRisk: tr('performancePage.groupRisk'),
    groupBooks: tr('performancePage.groupBooks'),
    mVol: tr('performancePage.mVol'),
    mVolInfo: tr('performancePage.mVolInfo'),
    mSortino: tr('performancePage.mSortino'),
    mSortinoInfo: tr('performancePage.mSortinoInfo'),
    mCalmar: tr('performancePage.mCalmar'),
    mCalmarInfo: tr('performancePage.mCalmarInfo'),
    mBeta: tr('performancePage.mBeta'),
    mBetaInfo: tr('performancePage.mBetaInfo'),
    mAlpha: tr('performancePage.mAlpha'),
    mAlphaInfo: tr('performancePage.mAlphaInfo'),
    mIrr: tr('performancePage.mIrr'),
    mIrrInfo: tr('performancePage.mIrrInfo'),
    mMv: tr('performancePage.mMv'),
    mMvInfo: tr('performancePage.mMvInfo'),
    mCost: (v: string) => tr('performancePage.mCost', { v }),
    mUpl: tr('performancePage.mUpl'),
    mUplInfo: tr('performancePage.mUplInfo'),
    mRpl: tr('performancePage.mRpl'),
    mRplInfo: tr('performancePage.mRplInfo'),
    mDiv: tr('performancePage.mDiv'),
    mDivInfo: tr('performancePage.mDivInfo'),
    mCash: tr('performancePage.mCash'),
    mCashInfo: tr('performancePage.mCashInfo'),
    mTotal: tr('performancePage.mTotal'),
    mTotalInfo: tr('performancePage.mTotalInfo'),
    monthly: tr('performancePage.monthly'),
    monthlyInfo: tr('performancePage.monthlyInfo'),
    rowPortfolio: tr('performancePage.rowPortfolio'),
    rowPortfolioSub: tr('performancePage.rowPortfolioSub'),
    rowSpy: tr('performancePage.rowSpy'),
    rowSpySub: tr('performancePage.rowSpySub'),
    rowDiff: tr('performancePage.rowDiff'),
    rowDiffSub: tr('performancePage.rowDiffSub'),
    year: tr('performancePage.year'),
    inProgress: tr('performancePage.inProgress'),
    attribution: tr('performancePage.attribution'),
    attributionInfo: tr('performancePage.attributionInfo'),
    attributionRecon: (twr: string, d: string) => tr('performancePage.attributionRecon', { twr, d }),
    colTitle: tr('performancePage.colTitle'),
    colContribution: tr('performancePage.colContribution'),
    colWeight: tr('performancePage.colWeight'),
    local: tr('performancePage.local'),
    fx: tr('performancePage.fx'),
    avgWeight: tr('performancePage.avgWeight'),
    estimated: tr('performancePage.estimated'),
    estimatedNote: (g: number, t: number) => tr('performancePage.estimatedNote', { g, t }),
    openRow: (t: string) => tr('performancePage.openRow', { t }),
    bySector: tr('performancePage.bySector'),
    sectors: (n: number) => n === 1 ? tr('performancePage.sectors_one') : tr('performancePage.sectors_other', { n }),
    unclassified: tr('performancePage.unclassified'),
    titles: (n: number) => n === 1 ? tr('performancePage.titles_one') : tr('performancePage.titles_other', { n }),
    colSector: tr('performancePage.colSector'),
    fxLine: (cy: string, fx: string) => tr('performancePage.fxLine', { cy, fx }),
    fxAll: (cy: string) => cy === 'EUR' ? tr('performancePage.fxAll_eur') : tr('performancePage.fxAll', { cy }),
    calculating: tr('performancePage.calculating'),
    unavailable: tr('performancePage.unavailable'),
    retry: tr('performancePage.retry'),
    potentialLoss: tr('performancePage.potentialLoss'),
    potentialLossInfo: (n: number) => tr('performancePage.potentialLossInfo', { n }),
    ofNav: (v: string) => tr('performancePage.ofNav', { v }),
    varHist: tr('performancePage.varHist'),
    var99: tr('performancePage.var99'),
    var99Info: tr('performancePage.var99Info'),
    relVol: tr('performancePage.relVol'),
    relVolSub: (v: string) => tr('performancePage.relVolSub', { v }),
    distribution: tr('performancePage.distribution'),
    distributionInfo: tr('performancePage.distributionInfo'),
    negSessions: tr('performancePage.negSessions'),
    posSessions: tr('performancePage.posSessions'),
    distSummary: (n: number, k: number, e: number, pd: string, pv: string, mv: string) => tr('performancePage.distSummary', { n, k, e, pd, pv, mv }),
    distNoVar: tr('performancePage.distNoVar'),
    distSummaryNoVar: (n: number, pd: string, pv: string, mv: string) => tr('performancePage.distSummaryNoVar', { n, pd, pv, mv }),
    distExcludedNoFlow: (k: number, date: string) => tr('performancePage.distExcludedNoFlow', { k, date }),
    distFlowsMisaligned: tr('performancePage.distFlowsMisaligned'),
    liquidity: tr('performancePage.liquidity'),
    liquidityInfo: (quota: string, verde: string, giallo: string) => tr('performancePage.liquidityInfo', { quota, verde, giallo }),
    liqPosition: tr('performancePage.liqPosition'),
    liqAdv: tr('performancePage.liqAdv'),
    liqDays: tr('performancePage.liqDays'),
    liqDaysValue: (g: string) => tr('performancePage.liqDaysValue', { g }),
    liqScoreCol: tr('performancePage.liqScoreCol'),
    liqNd: tr('performancePage.liqNd'),
    liqNoRows: tr('performancePage.liqNoRows'),
    liqNoVolume: tr('performancePage.liqNoVolume'),
    liqNote: (nota: string) => tr('performancePage.liqNote', { nota }),
    liqScore: {
      green: tr('performancePage.liqScore_green'), yellow: tr('performancePage.liqScore_yellow'), red: tr('performancePage.liqScore_red'),
      skip: tr('performancePage.liqScore_skip'), unknown: tr('performancePage.liqScore_unknown'), error: tr('performancePage.liqScore_error'),
    } as Record<string, string>,
    binTitle: (n: number, a: string, b: string) => tr('performancePage.binTitle', { n, a, b }),
    contribution: tr('performancePage.contribution'),
    contributionInfo: tr('performancePage.contributionInfo'),
    colVarShare: tr('performancePage.colVarShare'),
    colRisk: tr('performancePage.colRisk'),
    aboveWeight: tr('performancePage.aboveWeight'),
    diversifying: tr('performancePage.diversifying'),
    others: (n: number, v: string) => tr('performancePage.others', { n, v }),
    onlyTop: tr('performancePage.onlyTop'),
    effN: (v: string) => tr('performancePage.effN', { v }),
    hhi: (c: string, v: string) => tr('performancePage.hhi', { c, v }),
    classification: { diversified: tr('performancePage.classification_diversified'), moderate: tr('performancePage.classification_moderate'), concentrated: tr('performancePage.classification_concentrated') } as Record<string, string>,
    regionNames: { EU: tr('performancePage.regionNames_EU'), US: tr('performancePage.regionNames_US'), ASIA: tr('performancePage.regionNames_ASIA'), EM: tr('performancePage.regionNames_EM'), OTHER: tr('performancePage.regionNames_OTHER') } as Record<string, string>,
    regionSub: (c: string) => tr('performancePage.regionSub', { c }),
    currencySub: tr('performancePage.currencySub'),
    currencyMixed: tr('performancePage.currencyMixed'),
    market: tr('performancePage.market'),
    marketInfo: (n: number) => tr('performancePage.marketInfo', { n }),
    levelSpy: tr('performancePage.levelSpy'),
    cVol: tr('performancePage.cVol'),
    cVolSub: (p: string, s: string) => tr('performancePage.cVolSub', { p, s }),
    cVar: tr('performancePage.cVar'),
    cVarSub: (p: string, s: string) => tr('performancePage.cVarSub', { p, s }),
    cDd: tr('performancePage.cDd'),
    cDdSub: (p: string, s: string) => tr('performancePage.cDdSub', { p, s }),
    cBeta: tr('performancePage.cBeta'),
    betaSpecific: (b: string) => tr('performancePage.betaSpecific', { b }),
    betaMarket: (b: string) => tr('performancePage.betaMarket', { b }),
    cSharpe: tr('performancePage.cSharpe'),
    cSharpeSub: (p: string, s: string) => tr('performancePage.cSharpeSub', { p, s }),
    riskLevel: { basso: tr('performancePage.riskLevel_basso'), medio: tr('performancePage.riskLevel_medio'), alto: tr('performancePage.riskLevel_alto') } as Record<string, string>,
    drawdown: tr('performancePage.drawdown'),
    drawdownInfo: tr('performancePage.drawdownInfo'),
    ddNow: (d: string, max: string) => tr('performancePage.ddNow', { d, max }),
    ddNone: tr('performancePage.ddNone'),
    ddTop: tr('performancePage.ddTop'),
    ddPeak: tr('performancePage.ddPeak'),
    ddTrough: tr('performancePage.ddTrough'),
    ddDepth: tr('performancePage.ddDepth'),
    ddRecovery: tr('performancePage.ddRecovery'),
    ddOpen: tr('performancePage.ddOpen'),
    ddOpenToday: (v: string) => tr('performancePage.ddOpenToday', { v }),
    ddRecovered: (n: string, d: string) => tr('performancePage.ddRecovered', { n, d }),
    ddDays: (n: number) => n === 1 ? tr('performancePage.ddDays_one') : tr('performancePage.ddDays_other', { n }),
    stress: tr('performancePage.stress'),
    stressInfo: tr('performancePage.stressInfo'),
    stressSub: tr('performancePage.stressSub'),
    scenarios: {
      none: [tr('performancePage.scenarios_none'), tr('performancePage.scenarios_none_hint')],
      shock_3sigma: [tr('performancePage.scenarios_shock_3sigma'), tr('performancePage.scenarios_shock_3sigma_hint')],
      gfc_2008: [tr('performancePage.scenarios_gfc_2008'), tr('performancePage.scenarios_gfc_2008_hint')],
      covid_2020: [tr('performancePage.scenarios_covid_2020'), tr('performancePage.scenarios_covid_2020_hint')],
    } as Record<IdScenario, [string, string]>,
    medianLoss: tr('performancePage.medianLoss'),
    worst5: tr('performancePage.worst5'),
    probLoss10: tr('performancePage.probLoss10'),
    es95: (v: string) => tr('performancePage.es95', { v }),
    replayLoss: tr('performancePage.replayLoss'),
    replayGain: tr('performancePage.replayGain'),
    replayOutcome: tr('performancePage.replayOutcome'),
    replayNote: tr('performancePage.replayNote'),
    replayFallback: tr('performancePage.replayFallback'),
    proxied: (t: string) => tr('performancePage.proxied', { t }),
    mWarn: tr('performancePage.mWarn'),
    mTwr: tr('performancePage.mTwr'),
    mCoverage: tr('performancePage.mCoverage'),
    mBench: tr('performancePage.mBench'),
    mAttr: tr('performancePage.mAttr'),
    mRisk: tr('performancePage.mRisk'),
    mScen: tr('performancePage.mScen'),
    mNotes: tr('performancePage.mNotes'),
    mRecon: tr('performancePage.mRecon'),
    mBase: tr('performancePage.mBase'),
    mOfficialSince: tr('performancePage.mOfficialSince'),
    mGaps: tr('performancePage.mGaps'),
    mFirstTrade: tr('performancePage.mFirstTrade'),
    mFirstSnap: tr('performancePage.mFirstSnap'),
    mTradesBefore: tr('performancePage.mTradesBefore'),
    mCoveragePct: tr('performancePage.mCoveragePct'),
    mCarry: tr('performancePage.mCarry'),
    mSource: tr('performancePage.mSource'),
    mExcluded: (t: string) => tr('performancePage.mExcluded', { t }),
    mExcludedDays: (g: number, t: number, why: string) => why ? tr('performancePage.mExcludedDays_why', { g, t, why }) : tr('performancePage.mExcludedDays', { g, t }),
    mVsTwr: tr('performancePage.mVsTwr'),
    mLookback: tr('performancePage.mLookback'),
    mLookbackDays: (n: number) => tr('performancePage.mLookbackDays', { n }),
    mNavLive: tr('performancePage.mNavLive'),
    mLastSnap: (d: string) => tr('performancePage.mLastSnap', { d }),
    mDelta: tr('performancePage.mDelta'),
    dataUnavailable: (src: string, why: string) => tr('performancePage.dataUnavailable', { src, why }),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
