import { linguaCorrente, type Lingua } from '@/i18n/lingua';
import { traduci, type Chiave, type Parametri } from '@/i18n/t';



// I testi stanno nel catalogo (i18n/it|en/agentsPage.ts): qui solo la forma che le viste usano.

/** Un motivo del backend dentro una frase che chiude col suo punto: via la punteggiatura
 *  finale del motivo (. ! ?), o la frase finirebbe con «..» o «!.» (review PR #19). */
export function senzaPuntoFinale(testo: string): string {
  return testo.replace(/[\s.!?]+$/u, '');
}
function costruisci(l: Lingua) {
  const tr = (k: Chiave, p?: Record<string, string | number | null | undefined>) => traduci(l, k, p as Parametri | undefined);
  /* strumento → [frase senza ticker, frase con ticker] */
  const frasi: Record<string, [string, ((tk: string) => string) | null]> = {
      ask_specialist: [tr('agentsPage.do_ask_specialist'), null],
      build_dcf_model: [tr('agentsPage.do_build_dcf_model'), (tk: string) => tr('agentsPage.do_build_dcf_model_tk', { t: tk })],
      compare_assets: [tr('agentsPage.do_compare_assets'), null],
      get_13f_filing: [tr('agentsPage.do_get_13f_filing'), null],
      get_congress_trades: [tr('agentsPage.do_get_congress_trades'), null],
      get_filing_changes: [tr('agentsPage.do_get_filing_changes'), (tk: string) => tr('agentsPage.do_get_filing_changes_tk', { t: tk })],
      get_fundamentals: [tr('agentsPage.do_get_fundamentals'), (tk: string) => tr('agentsPage.do_get_fundamentals_tk', { t: tk })],
      get_gov_contracts: [tr('agentsPage.do_get_gov_contracts'), null],
      get_hyperliquid_intel: [tr('agentsPage.do_get_hyperliquid_intel'), null],
      get_insider_trades: [tr('agentsPage.do_get_insider_trades'), (tk: string) => tr('agentsPage.do_get_insider_trades_tk', { t: tk })],
      get_lobbying: [tr('agentsPage.do_get_lobbying'), null],
      get_macro_dashboard: [tr('agentsPage.do_get_macro_dashboard'), null],
      get_macro_indicator: [tr('agentsPage.do_get_macro_indicator'), null],
      get_market_data: [tr('agentsPage.do_get_market_data'), (tk: string) => tr('agentsPage.do_get_market_data_tk', { t: tk })],
      get_options_data: [tr('agentsPage.do_get_options_data'), (tk: string) => tr('agentsPage.do_get_options_data_tk', { t: tk })],
      get_polymarket_events: [tr('agentsPage.do_get_polymarket_events'), null],
      get_portfolio_live: [tr('agentsPage.do_get_portfolio_live'), null],
      get_portfolio_state: [tr('agentsPage.do_get_portfolio_state'), null],
      get_yield_curves: [tr('agentsPage.do_get_yield_curves'), null],
      quant_compute: [tr('agentsPage.do_quant_compute'), (tk: string) => tr('agentsPage.do_quant_compute_tk', { t: tk })],
      read_blackboard: [tr('agentsPage.do_read_blackboard'), null],
      read_recent_briefings: [tr('agentsPage.do_read_recent_briefings'), null],
      search_news: [tr('agentsPage.do_search_news'), (tk: string) => tr('agentsPage.do_search_news_tk', { t: tk })],
      tavily_search: [tr('agentsPage.do_tavily_search'), null],
  };
  const esitoPill: Record<string, () => string> = {
    in_corso: () => tr('agentsPage.esitoPill_in_corso'), in_corso_senza_segnale: () => tr('agentsPage.esitoPill_in_corso_senza_segnale'),
    completata: () => tr('agentsPage.esitoPill_completata'), incompleta: () => tr('agentsPage.esitoPill_incompleta'),
    bloccata: () => tr('agentsPage.esitoPill_bloccata'), fallita: () => tr('agentsPage.esitoPill_fallita'),
    annullata: () => tr('agentsPage.esitoPill_annullata'), interrotta: () => tr('agentsPage.esitoPill_interrotta'),
    nessuna_run: () => tr('agentsPage.esitoPill_nessuna_run'), sconosciuta: () => tr('agentsPage.esitoPill_sconosciuta'),
  };
  const esitoTitolo: Record<string, () => string> = {
    incompleta: () => tr('agentsPage.esitoTitle_incompleta'), bloccata: () => tr('agentsPage.esitoTitle_bloccata'),
    fallita: () => tr('agentsPage.esitoTitle_fallita'), annullata: () => tr('agentsPage.esitoTitle_annullata'),
    interrotta: () => tr('agentsPage.esitoTitle_interrotta'), sconosciuta: () => tr('agentsPage.esitoTitle_sconosciuta'),
  };
  const memoFrase = (memo: boolean | null, id: number | null) => memo === true
    ? (id != null ? tr('agentsPage.memoDelivered_id', { memo: id }) : tr('agentsPage.memoDelivered'))
    : memo === false ? tr('agentsPage.memoNotDelivered') : tr('agentsPage.memoUnmeasured');
  return {
    titleLive: tr('agentsPage.titleLive'),
    titleSynthesis: tr('agentsPage.titleSynthesis'),
    titleDone: (memo: number | null) => memo != null ? tr('agentsPage.titleDone_memo', { memo }) : tr('agentsPage.titleDone'),
    titleDoneNoMemo: tr('agentsPage.titleDoneNoMemo'),
    titleDoneMemoUnmeasured: tr('agentsPage.titleDoneMemoUnmeasured'),
    titleIdle: tr('agentsPage.titleIdle'),
    titleUnreadable: tr('agentsPage.titleUnreadable'),
    descLive: tr('agentsPage.descLive'),
    descIdle: (n: number) => n === 1 ? tr('agentsPage.descIdle_one') : tr('agentsPage.descIdle_other', { n }),
    descDone: (nDesk: number, nRound: number) => tr('agentsPage.descDone', { desks: nDesk === 1 ? tr('agentsPage.descDone_desk_one') : tr('agentsPage.descDone_desk_other', { n: nDesk }), rounds: nRound === 1 ? tr('agentsPage.descDone_round_one') : tr('agentsPage.descDone_round_other', { n: nRound }) }),
    descDoneNoMemo: tr('agentsPage.descDoneNoMemo'),
    descUnreadable: (ora: string | null) => ora ? tr('agentsPage.descUnreadable_at', { ora }) : tr('agentsPage.descUnreadable'),
    pillRunning: tr('agentsPage.pillRunning'),
    pillStuck: tr('agentsPage.pillStuck'),
    pillDone: tr('agentsPage.pillDone'),
    pillEnded: tr('agentsPage.pillEnded'),
    // esito vero della run (esito_run, 06/10): una voce per stato, «sconosciuta» per i valori fuori contratto
    pillEsito: (stato: string) => (esitoPill[stato] ?? esitoPill.sconosciuta)(),
    titleEsito: (stato: string) => (esitoTitolo[stato] ?? esitoTitolo.sconosciuta)(),
    memoEsito: (memo: boolean | null, id: number | null) => memoFrase(memo, id),
    descEsito: (stato: string, motivo: string | null, memo: boolean | null, id: number | null, ripresa: boolean) => {
      if (stato === 'interrotta') return tr('agentsPage.esitoDesc_interrotta');
      if (stato === 'annullata') return tr('agentsPage.esitoDesc_annullata');
      // «bloccata» dice gia' nel titolo che nessun memo e' stato consegnato
      const m = motivo ? senzaPuntoFinale(motivo) : '';
      return [m ? tr('agentsPage.esitoReason', { motivo: m }) : tr('agentsPage.esitoNoReason'),
        stato === 'bloccata' ? '' : memoFrase(memo, id), ripresa ? tr('agentsPage.esitoResumable') : ''].filter(Boolean).join(' ');
    },
    titleStarting: tr('agentsPage.titleStarting'),
    descStarting: tr('agentsPage.descStarting'),
    pillStarting: tr('agentsPage.pillStarting'),
    titleUnverified: tr('agentsPage.titleUnverified'),
    descUnverified: tr('agentsPage.descUnverified'),
    pillUnverified: tr('agentsPage.pillUnverified'),
    descNoCommittee: tr('agentsPage.descNoCommittee'),
    sNoRunCost: tr('agentsPage.sNoRunCost'),
    stepResumed: tr('agentsPage.stepResumed'),
    stepPartlyResumed: tr('agentsPage.stepPartlyResumed'),
    resumeAvailable: tr('agentsPage.resumeAvailable'),
    resumeOpen: tr('agentsPage.resumeOpen'),
    /* righe di tentativi_falliti_poi_riusciti: conteggio o round assenti si dichiarano n.d. (mai «undefined») */
    retriedBeforeSuccess: (desk: string, n: unknown, r: unknown) => {
      const round = typeof r === 'number' && Number.isFinite(r) ? r : tr('activity.unavailable');
      if (typeof n !== 'number' || !Number.isFinite(n)) return tr('agentsPage.retriedBeforeSuccess_nd', { desk, n: tr('activity.unavailable'), r: round });
      return tr(n === 1 ? 'agentsPage.retriedBeforeSuccess_one' : 'agentsPage.retriedBeforeSuccess', { desk, n, r: round });
    },
    attemptsBanner: (n: number, tot: number) => n === 1 ? tr('agentsPage.attemptsBanner_one', { tot }) : tr('agentsPage.attemptsBanner_other', { n, tot }),
    attemptsOldSemantics: tr('agentsPage.attemptsOldSemantics'),
    attemptsFinalOk: (desks: string) => tr('agentsPage.attemptsFinalOk', { desks }),
    attemptsFinalNd: (desks: string) => tr('agentsPage.attemptsFinalNd', { desks }),
    attemptsShort: (n: number) => n === 1 ? tr('agentsPage.attemptsShort_one') : tr('agentsPage.attemptsShort_other', { n }),
    stUnconfirmed: tr('agentsPage.stUnconfirmed'),
    unconfirmedDoing: tr('agentsPage.unconfirmedDoing'),
    stepUnconfirmed: tr('agentsPage.stepUnconfirmed'),
    nowUnconfirmed: tr('agentsPage.nowUnconfirmed'),
    sLastKnown: (ora: string) => tr('agentsPage.sLastKnown', { ora }),
    sClockStopped: tr('agentsPage.sClockStopped'),
    kNoRunCost: tr('agentsPage.kNoRunCost'),
    shareKnownOnly: (n: number) => n === 0 ? tr('agentsPage.shareKnownOnly_partial') : n === 1 ? tr('agentsPage.shareKnownOnly_one') : tr('agentsPage.shareKnownOnly', { n }),
    pillIdle: tr('agentsPage.pillIdle'),
    pillUnreadable: tr('agentsPage.pillUnreadable'),
    pillQuerying: tr('agentsPage.pillQuerying'),
    startedAt: (ora: string) => tr('agentsPage.startedAt', { ora }),
    runSpan: (giorno: string, da: string, a: string) => tr('agentsPage.runSpan', { giorno, da, a }),
    lastRun: tr('agentsPage.lastRun'),
    kDuration: tr('agentsPage.kDuration'),
    kCostSoFar: tr('agentsPage.kCostSoFar'),
    kCost: tr('agentsPage.kCost'),
    kCalls: tr('agentsPage.kCalls'),
    kTickers: tr('agentsPage.kTickers'),
    kParallelism: tr('agentsPage.kParallelism'),
    kOutcome: tr('agentsPage.kOutcome'),
    sClock: tr('agentsPage.sClock'),
    sWork: (lavoro: string) => tr('agentsPage.sWork', { lavoro }),
    sLast50: tr('agentsPage.sLast50'),
    sDistinctTools: (n: number) => n === 1 ? tr('agentsPage.sDistinctTools_one') : tr('agentsPage.sDistinctTools_other', { n }),
    sTickersSoFar: tr('agentsPage.sTickersSoFar'),
    sTickers: (n: number) => n === 1 ? tr('agentsPage.sTickers_one') : tr('agentsPage.sTickers_other', { n }),
    sTogether: tr('agentsPage.sTogether'),
    sSoFarPartial: tr('agentsPage.sSoFarPartial'),
    sSoFar: tr('agentsPage.sSoFar'),
    sPartial: tr('agentsPage.sPartial'),
    sComplete: tr('agentsPage.sComplete'),
    sUnpriced: tr('agentsPage.sUnpriced'),
    sKoSpent: (eur: string) => tr('agentsPage.sKoSpent', { eur }),
    outcomeOk: tr('agentsPage.outcomeOk'),
    outcomeKo: (n: number) => n === 1 ? tr('agentsPage.outcomeKo_one') : tr('agentsPage.outcomeKo_other', { n }),
    launch: tr('agentsPage.launch'),
    newRun: tr('agentsPage.newRun'),
    stop: tr('agentsPage.stop'),
    stopping: tr('agentsPage.stopping'),
    openDecisions: tr('agentsPage.openDecisions'),
    memoArchive: tr('agentsPage.memoArchive'),
    memo: (id: number) => tr('agentsPage.memo', { id }),
    steps: tr('agentsPage.steps'),
    stepStart: tr('agentsPage.stepStart'),
    stepRound: (r: number) => tr('agentsPage.stepRound', { r }),
    stepSynthesis: tr('agentsPage.stepSynthesis'),
    stepMemo: tr('agentsPage.stepMemo'),
    stepWaiting: tr('agentsPage.stepWaiting'),
    stepDone: tr('agentsPage.stepDone'),
    stepNow: (dur: string) => tr('agentsPage.stepNow', { dur }),
    stepNowShort: tr('agentsPage.stepNowShort'),
    stepStale: (dur: string) => tr('agentsPage.stepStale', { dur }),
    stepSkipped: tr('agentsPage.stepSkipped'),
    stepRoundNd: tr('agentsPage.stepRoundNd'),
    stepNoMemo: tr('agentsPage.stepNoMemo'),
    nowRound: (r: number) => tr('agentsPage.nowRound', { r }),
    nowWorking: (n: number, tot: number, done: number) => tr(tot === 1 ? 'agentsPage.nowWorking_one' : 'agentsPage.nowWorking', { n, tot, done: done ? (done === 1 ? tr('agentsPage.nowWorking_done_one') : tr('agentsPage.nowWorking_done_other', { done })) : '' }),
    nowBetween: tr('agentsPage.nowBetween'),
    nowSynthesis: tr('agentsPage.nowSynthesis'),
    nowCapo: tr('agentsPage.nowCapo'),
    nowCapoNote: tr('agentsPage.nowCapoNote'),
    nowStarting: tr('agentsPage.nowStarting'),
    nowStale: (dur: string) => tr('agentsPage.nowStale', { dur }),
    nowStaleSub: (ora: string) => tr('agentsPage.nowStaleSub', { ora }),
    desks: tr('agentsPage.desks'),
    stWorking: tr('agentsPage.stWorking'),
    stThinking: tr('agentsPage.stThinking'),
    stDone: tr('agentsPage.stDone'),
    stKo: tr('agentsPage.stKo'),
    stNd: tr('agentsPage.stNd'),
    stWaiting: tr('agentsPage.stWaiting'),
    stStale: tr('agentsPage.stStale'),
    doingAgo: (input: string, ago: string) => input ? tr('agentsPage.doingAgo_input', { input, ago }) : tr('agentsPage.doingAgo', { ago }),
    thinkingSince: (dur: string) => tr('agentsPage.thinkingSince', { dur }),
    lastTool: (tool: string) => tr('agentsPage.lastTool', { tool }),
    noCallYet: tr('agentsPage.noCallYet'),
    noCallYetSub: tr('agentsPage.noCallYetSub'),
    staleDoing: (dur: string) => tr('agentsPage.staleDoing', { dur }),
    delivered: tr('agentsPage.delivered'),
    deliveredRound: (r: number) => tr('agentsPage.deliveredRound', { r }),
    rounds: (n: number) => n === 1 ? tr('agentsPage.rounds_one') : tr('agentsPage.rounds_other', { n }),
    notInR2: tr('agentsPage.notInR2'),
    at: (ora: string) => tr('agentsPage.at', { ora }),
    koTitle: tr('agentsPage.koTitle'),
    waitingLive: tr('agentsPage.waitingLive'),
    waitingIdle: tr('agentsPage.waitingIdle'),
    calls: (n: number) => n === 1 ? tr('agentsPage.calls_one') : tr('agentsPage.calls_other', { n }),
    deskDetail: (strumenti: number, api: number, motore: string) => tr('agentsPage.deskDetail', { strumenti, api, motore }),
    capo: tr('agentsPage.capo'),
    capoWaiting: tr('agentsPage.capoWaiting'),
    capoWaitingSub: (done: number, tot: number) => tr('agentsPage.capoWaitingSub', { done, tot }),
    capoWriting: (dur: string) => tr('agentsPage.capoWriting', { dur }),
    capoWritingNoTime: tr('agentsPage.capoWritingNoTime'),
    capoWritingSub: (ora: string) => tr('agentsPage.capoWritingSub', { ora }),
    capoWritingStale: (dur: string) => tr('agentsPage.capoWritingStale', { dur }),
    capoSaved: (id: number) => tr('agentsPage.capoSaved', { id }),
    capoSavedSub: (dur: string, ora: string) => tr('agentsPage.capoSavedSub', { dur, ora }),
    capoNoMemo: tr('agentsPage.capoNoMemo'),
    capoNoMemoSub: tr('agentsPage.capoNoMemoSub'),
    capoIdle: tr('agentsPage.capoIdle'),
    capoPillWaiting: tr('agentsPage.capoPillWaiting'),
    capoPillWriting: tr('agentsPage.capoPillWriting'),
    capoPillDone: tr('agentsPage.capoPillDone'),
    stageRedTeam: tr('agentsPage.stageRedTeam'),
    stageReflection: tr('agentsPage.stageReflection'),
    stageActions: tr('agentsPage.stageActions'),
    stageAfter: tr('agentsPage.stageAfter'),
    stageNoDuration: tr('agentsPage.stageNoDuration'),
    panel: tr('agentsPage.panel'),
    tabCalls: tr('agentsPage.tabCalls'),
    tabTools: tr('agentsPage.tabTools'),
    tabTickers: tr('agentsPage.tabTickers'),
    callsTitle: tr('agentsPage.callsTitle'),
    costsTitle: tr('agentsPage.costsTitle'),
    lookedTitle: tr('agentsPage.lookedTitle'),
    lookedCount: (strumenti: number, ticker: number) => tr('agentsPage.lookedCount', { tools: strumenti === 1 ? tr('agentsPage.lookedCount_tool_one') : tr('agentsPage.lookedCount_tool_other', { n: strumenti }), tickers: ticker === 1 ? tr('agentsPage.lookedCount_ticker_one') : tr('agentsPage.lookedCount_ticker_other', { n: ticker }) }),
    last50Of: (n: number, tot: number | null) => tot != null ? tr('agentsPage.last50Of_of', { n, tot }) : tr('agentsPage.last50Of', { n }),
    allN: (n: number) => tr('agentsPage.allN', { n }),
    callsNow: tr('agentsPage.callsNow'),
    callsNewestFirst: tr('agentsPage.callsNewestFirst'),
    noCalls: tr('agentsPage.noCalls'),
    tokens: tr('agentsPage.tokens'),
    costPerAgent: tr('agentsPage.costPerAgent'),
    cacheNote: (x: string) => tr('agentsPage.cacheNote', { x }),
    sumEqual: (eur: string) => tr('agentsPage.sumEqual', { eur }),
    sumDiff: (eur: string, tot: string) => tr('agentsPage.sumDiff', { eur, tot }),
    sumMissing: (eur: string, n: number) => tr('agentsPage.sumMissing', { eur, n }),
    koInside: (eur: string, n: number) => n === 1 ? tr('agentsPage.koInside_one', { eur }) : tr('agentsPage.koInside_other', { eur, n }),
    engines: (desk: string, capo: string) => tr('agentsPage.engines', { desk, capo }),
    pillPartial: tr('agentsPage.pillPartial'),
    pillComplete: tr('agentsPage.pillComplete'),
    fx: tr('agentsPage.fx'),
    inProgressCost: tr('agentsPage.inProgressCost'),
    toolsFootLive: (n: number, tot: number | null) => tot != null ? tr('agentsPage.toolsFootLive_tot', { n, tot }) : tr('agentsPage.toolsFootLive', { n }),
    toolsFoot: (n: number, tot: number) => n === 1 ? tr('agentsPage.toolsFoot_one', { tot }) : tr('agentsPage.toolsFoot_other', { n, tot }),
    noTickers: tr('agentsPage.noTickers'),
    done: (ora: string, memo: number | null) => memo != null ? tr('agentsPage.done_memo', { ora, memo }) : tr('agentsPage.done', { ora }),
    backendDown: tr('agentsPage.backendDown'),
    backendDownSub: (dettaglio: string, ora: string | null) => {
      const d = senzaPuntoFinale(dettaglio);
      return ora ? tr('agentsPage.backendDownSub_at', { dettaglio: d, ora }) : tr('agentsPage.backendDownSub', { dettaglio: d });
    },
    koBanner: (n: number, tot: number) => n === 1 ? tr('agentsPage.koBanner_one', { tot }) : tr('agentsPage.koBanner_other', { n, tot }),
    stuck: tr('agentsPage.stuck'),
    stuckSub: (min: number) => tr('agentsPage.stuckSub', { min }),
    partialBanner: tr('agentsPage.partialBanner'),
    tabFiling: tr('agentsPage.tabFiling'),
    filingTitle: tr('agentsPage.filingTitle'),
    filingGloss: tr('agentsPage.filingGloss'),
    filingLine: (con: number, tot: number, mancanti: number) => mancanti ? tr('agentsPage.filingLine_missing', { con, tot, mancanti }) : tr('agentsPage.filingLine', { con, tot }),
    filingLineLoading: tr('agentsPage.filingLineLoading'),
    filingLineDown: tr('agentsPage.filingLineDown'),
    filingOpen: tr('agentsPage.filingOpen'),
    filingCount: (con: number, tot: number) => tr('agentsPage.filingCount', { con, tot }),
    filingCoverage: (n: number, tot: number) => tr(tot === 1 ? 'agentsPage.filingCoverage_one' : 'agentsPage.filingCoverage_other', { n, tot }),
    filingFresh: (n: number) => n === 1 ? tr('agentsPage.filingFresh_one') : tr('agentsPage.filingFresh_other', { n }),
    filingStale: (n: number) => n === 1 ? tr('agentsPage.filingStale_one') : tr('agentsPage.filingStale_other', { n }),
    filingNoProfile: (n: number) => tr('agentsPage.filingNoProfile', { n }),
    filingNoComparison: (n: number) => tr('agentsPage.filingNoComparison', { n }),
    filingExcluded: (n: number) => n === 1 ? tr('agentsPage.filingExcluded_one') : tr('agentsPage.filingExcluded_other', { n }),
    filingContext: tr('agentsPage.filingContext'),
    filingChars: (a: string, b: string) => tr('agentsPage.filingChars', { a, b }),
    filingOmitted: (n: number) => n === 1 ? tr('agentsPage.filingOmitted_one') : tr('agentsPage.filingOmitted_other', { n }),
    filingContextFull: tr('agentsPage.filingContextFull'),
    filingHoldings: tr('agentsPage.filingHoldings'),
    filingOpenPage: tr('agentsPage.filingOpenPage'),
    filingActivate: tr('agentsPage.filingActivate'),
    filingActivating: tr('agentsPage.filingActivating'),
    filingActivateHelp: tr('agentsPage.filingActivateHelp'),
    filingNoneMissing: tr('agentsPage.filingNoneMissing'),
    filingRunActive: tr('agentsPage.filingRunActive'),
    filingUnavailable: tr('agentsPage.filingUnavailable'),
    filingReadError: tr('agentsPage.filingReadError'),
    filingLoading: tr('agentsPage.filingLoading'),
    filingResult: (a: number, c: number, s: number) => a === 1 ? tr('agentsPage.filingResult_one', { c, s }) : tr('agentsPage.filingResult_other', { a, c, s }),
    filingToConfirm: tr('agentsPage.filingToConfirm'),
    filingToConfirmHelp: tr('agentsPage.filingToConfirmHelp'),
    filingNoSource: tr('agentsPage.filingNoSource'),
    filingErrors: tr('agentsPage.filingErrors'),
    filingQueued: tr('agentsPage.filingQueued'),
    filingStarted: tr('agentsPage.filingStarted'),
    filingRefreshing: tr('agentsPage.filingRefreshing'),
    filingRetry: tr('agentsPage.filingRetry'),
    // redesign «tavolo + corsie» (05/10/2026)
    tableLabel: tr('agentsPage.tableLabel'),
    nowTitle: tr('agentsPage.nowTitle'),
    nowIdle: tr('agentsPage.nowIdle'),
    nowDoneMemo: tr('agentsPage.nowDoneMemo'),
    lensTitle: tr('agentsPage.lensTitle'),
    lensEmpty: tr('agentsPage.lensEmpty'),
    lensCount: (n: number) => n === 1 ? tr('agentsPage.lensCount_one') : tr('agentsPage.lensCount_other', { n }),
    lensMore: (n: number) => tr('agentsPage.lensMore', { n }),
    costTitle: tr('agentsPage.costTitle'),
    figuresTitle: tr('agentsPage.figuresTitle'),
    costDetails: tr('agentsPage.costDetails'),
    costByDesk: tr('agentsPage.costByDesk'),
    elapsed: tr('agentsPage.elapsed'),
    reportsOf: (n: number, tot: number) => tr('agentsPage.reportsOf', { n, tot }),
    reportsN: (n: number) => n === 1 ? tr('agentsPage.reportsN_one') : tr('agentsPage.reportsN_other', { n }),
    runEnded: tr('agentsPage.runEnded'),
    legendTitle: tr('agentsPage.legendTitle'),
    legWorking: tr('agentsPage.legWorking'),
    legWaiting: tr('agentsPage.legWaiting'),
    legDone: tr('agentsPage.legDone'),
    legIdle: tr('agentsPage.legIdle'),
    legIssue: tr('agentsPage.legIssue'),
    capoReady: tr('agentsPage.capoReady'),
    conclTitle: tr('agentsPage.conclTitle'),
    conclHint: tr('agentsPage.conclHint'),
    conclEmpty: tr('agentsPage.conclEmpty'),
    lanesTitle: tr('agentsPage.lanesTitle'),
    lanesHint: tr('agentsPage.lanesHint'),
    lanesEmpty: tr('agentsPage.lanesEmpty'),
    lanesPartial: tr('agentsPage.lanesPartial'),
    lanesCapo: tr('agentsPage.lanesCapo'),
    lanesReport: tr('agentsPage.lanesReport'),
    lanesMemo: tr('agentsPage.lanesMemo'),
    detailsOpen: tr('agentsPage.detailsOpen'),
    detailsSub: tr('agentsPage.detailsSub'),
    tabCosts: tr('agentsPage.tabCosts'),
    tabRecovery: tr('agentsPage.tabRecovery'),
    close: tr('agentsPage.close'),
    reportPreview: tr('agentsPage.reportPreview'),
    reportWaiting: (r: number, nome: string) => tr('agentsPage.reportWaiting', { r, nome }),
    reportNone: tr('agentsPage.reportNone'),
    reportMissingRound: (r: number, nome: string) => tr('agentsPage.reportMissingRound', { r, nome }),
    reportTickers: tr('agentsPage.reportTickers'),
    /** Lo strumento detto in parole («Legge i bilanci di ACME»); null = strumento senza frase:
     *  la vista mostra il nome tecnico, mai una frase inventata. */
    faccio: (tool: string, tk: string | null): string | null => {
      const f = frasi[tool];
      if (!f) return null;
      return tk && f[1] ? f[1](tk) : f[0];
    },
    filingNotBlocking: tr('agentsPage.filingNotBlocking'),
    filingSecNotConfigured: tr('agentsPage.filingSecNotConfigured'),
  };
}

type Dizionario = ReturnType<typeof costruisci>;
const cache = new Map<Lingua, Dizionario>();

export function parole(): Dizionario {
  const l = linguaCorrente();
  let d = cache.get(l);
  if (!d) { d = costruisci(l); cache.set(l, d); }
  return d;
}
